project_name: sv

builds:
  - main: .
    binary: sv
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^Merge "

release:
  draft: false
